### ISSUE TITLE
running on windows throws error because windows doesn't have "uname" command

### ISSUE THREAD

**Issue by nomad-rst** [oyvindberg/tui-scala#31]
trying to run tui in windows throws an error because in [crossterm/src/java/tui/crossterm/NativeLoader.java](https://github.com/oyvindberg/tui-scala/blob/5da87988618cfc23024f12558c698c77ecf8d1d2/crossterm/src/java/tui/crossterm/NativeLoader.java) the **getPlatform** function tries to run the unix/linux command "uname" which doesn't exist in windows

**Comment by oyvindberg** [comment]
Hi there!

Ohhh, right. I remember I was a bit sceptic while porting that code when I saw it ran `uname`, but since I had recently learnt that at least newer windowses actually do have the `uname` command I figured it had to work. So that code is ported to java from sbt-jni, and now I found https://github.com/sbt/sbt-jni/issues/20 .

**Comment by oyvindberg** [comment]
released 0.0.5 with the fix. I honestly haven't tested it as good as I should, but it passed CI on all four supported platforms
