### ISSUE TITLE
running the examples on windows after cloning the repository throws an error

### ISSUE THREAD

**Issue by nomad-scl** [oyvindberg/tui-scala#33]
trying to run the demo examples on windows -using intellij- after cloning the repository throws the following error

Exception in thread "main" java.lang.UnsatisfiedLinkError: Native library crossterm.dll (/native/x86_64-windows/crossterm.dll) cannot be found on the classpath.

the IDE isn't reporting any errors and running the command "bleep run demo@jvm213 <demoname>" on the contribution page runs all the examples but when trying to run them from the IDE it throws the error above

**Comment by oyvindberg** [comment]
Thanks for reporting. I should note that running the examples in intellij doesn't work very well in any case, because the terminal you get there does not allow you to enter into raw mode. All the demos require that, though the library can be used to write applications without raw mode.

That said, this should work up until where it fails to enter raw mode.
Can you ensure that you have ran `bleep generate-jni-library` first? And the perhaps try a `BSP reload` in intellij after it has been produces?

I don't have windows myself, so if I don't get more information it'll likely take long to solve

**Comment by oyvindberg** [comment]
I'll just have to guess this was not running `bleep generate-jni-library` for now. This will be automatic from now on
